update xihe-server, async-server, message-server config for points
opensourceways/infra-mindspore pull request #1234
Opened 2023-09-18 07:36 UTC by VictorZhou123

2023-09-18 09:18 UTC, pkking commented
lgtm

2023-09-18 10:36 UTC, zengchen1024 requested changes

2023-09-18 10:36 UTC, zengchen1024 commented on applications/xihe-test-v2/async-server/configmap.yaml
> +        bigmodel_access_log:
少了 picture_like

2023-09-18 10:36 UTC, zengchen1024 commented on applications/xihe-test-v2/message-server/configmap.yaml
> -
保留空行

2023-09-18 10:36 UTC, zengchen1024 commented on applications/xihe-test-v2/xihe-server/configmap.yaml
> +
不要加空格

2023-09-18 10:36 UTC, zengchen1024 commented on applications/xihe-test-v2/xihe-server/configmap.yaml
> +        picture_publicized:
少了 picture_like https://github.com/opensourceways/xihe-server/blob/dev/bigmodel/infrastructure/messageadapter/impl.go#L138

2023-09-18 10:55 UTC, VictorZhou123 commented on applications/xihe-test-v2/async-server/configmap.yaml
> +        bigmodel_access_log:
> 少了 picture_like

done

2023-09-18 10:56 UTC, VictorZhou123 commented on applications/xihe-test-v2/xihe-server/configmap.yaml
> +
> 不要加空格

done

2023-09-18 10:56 UTC, VictorZhou123 commented on applications/xihe-test-v2/xihe-server/configmap.yaml
> +        picture_publicized:
> 少了 picture_like https://github.com/opensourceways/xihe-server/blob/dev/bigmodel/infrastructure/messageadapter/impl.go#L138

done

2023-09-18 10:56 UTC, VictorZhou123 commented on applications/xihe-test-v2/message-server/configmap.yaml
> -
> 保留空行

done

2023-09-18 11:00 UTC, zengchen1024 requested changes

2023-09-18 11:00 UTC, zengchen1024 commented on applications/xihe-test-v2/async-server/configmap.yaml
> +        bigmodel_access_log:
picture_liked key是错误的，要么你修改下xihe的代码

2023-09-18 11:58 UTC, VictorZhou123 commented on applications/xihe-test-v2/async-server/configmap.yaml
> +        bigmodel_access_log:
> picture_liked key是错误的，要么你修改下xihe的代码

https://github.com/opensourceways/xihe-server/pull/569

2023-09-19 01:11 UTC, zengchen1024 approved these changes

2023-09-19 01:12 UTC, merged